-- Import FPJJ Teams
INSERT INTO teams (name, professor, city, state) VALUES
('ALLIANCE', 'Fabio Gurgel', 'São Paulo', 'SP'),
('ATOS JIU-JITSU', 'Andre Galvao', 'São Paulo', 'SP'),
('CHECKMAT', 'Leo Vieira', 'São Paulo', 'SP'),
('GRACIE BARRA', 'Carlos Gracie Jr.', 'Rio de Janeiro', 'RJ'),
('GF TEAM', 'Julio Cesar Pereira', 'Rio de Janeiro', 'RJ'),
('NOVA UNIÃO', 'Wendell Alexander', 'Rio de Janeiro', 'RJ'),
('PSLPB CICERO COSTHA', 'Cicero Costha', 'São Paulo', 'SP'),
('ZENITH BJJ', 'Robert Drysdale', 'Santos', 'SP'),
('BARBOSA JIU-JITSU', 'Marco Barbosa', 'São Paulo', 'SP'),
('GUIGO JIU-JITSU', 'Luiz Guilherme', 'São Paulo', 'SP'),
('NS BROTHERHOOD', 'Leandro Lo', 'São Paulo', 'SP'),
('CARLSON GRACIE TEAM', 'Carlson Gracie', 'Rio de Janeiro', 'RJ'),
('LOTUS CLUB', 'Moises Muradi', 'São Paulo', 'SP'),
('CANTAGALO TEAM', 'Douglas Rufino', 'São Paulo', 'SP'),
('COHAB JIU-JITSU', 'Danilo Silveira', 'São Paulo', 'SP'),
('G13 BJJ', 'Roberto Godoi', 'São Paulo', 'SP'),
('TEAM SYLVIO BEHRING', 'Sylvio Behring', 'Rio de Janeiro', 'RJ'),
('B9 JIU-JITSU', 'Marco Barbosa', 'São Paulo', 'SP'),
('ROGERS JIU-JITSU', 'Roger Gracie', 'Rio de Janeiro', 'RJ'),
('MARCIO RODRIGUES', 'Marcio Rodrigues', 'Rio de Janeiro', 'RJ'),
('GRACIE HUMAITÁ', 'Rolker Gracie', 'Rio de Janeiro', 'RJ'),
('A-FORCE BJJ', 'Andre Monteiro', 'Rio de Janeiro', 'RJ'),
('ALMEIDA JJ', 'Caio Almeida', 'São Paulo', 'SP'),
('BONSAI JJ', 'Mauricio Dai de Souza', 'São Paulo', 'SP'),
('CERO BJJ', 'Cero', 'São Paulo', 'SP'),
('EQUIPE A', 'Mestre A', 'São Paulo', 'SP'),
('EQUIPE B', 'Mestre B', 'São Paulo', 'SP'),
('FPJJ - FEDERAÇÃO PAULISTA DE JIU-JITSU', 'Diretoria', 'São Paulo', 'SP')
ON CONFLICT (name) DO NOTHING;
